### PR TITLE
Make it work with current version of `npm audit`

### PR DESCRIPTION
**Pull request by wilgert**

### CODE REVIEW

**Comment by revathskumar** [comment]
@wilgert Thanks for the PR.

I was thinking let's use `npm audit --json` and use the json to find this. 
That will be much simpler and avoid future breakages like this.

**Comment by wilgert** [comment]
That's indeed a better approach. Shall I implement it and create a new PR or do you want to do it yourself?

**Comment by revathskumar** [comment]
@wilgert Please go ahead and implement. 
I am happy to merge and do a release.

**Comment by wilgert** [comment]
This one can be closed as i have created a separate PR: #7

**Pull request closed without merging**
